import { DollarSign } from 'lucide-react';

import { EmptyState } from '@/components/shared';

export default function FeesPage() {
  return (
    <EmptyState
      icon={DollarSign}
      title="Fees"
      description="Track recruitment revenue generated by placements."
      actionLabel="Add Fee"
    />
  );
}
