#!/usr/bin/env sh
# Regenerates infrastructure/nginx/cloudflare-ips.conf from Cloudflare's published ranges.
# Run occasionally (or from CI on a schedule) and commit the diff.
set -eu

OUT="$(dirname "$0")/../nginx/cloudflare-ips.conf"
TMP="$(mktemp)"

{
  echo "# Generated by infrastructure/scripts/update-cloudflare-ips.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# Source: https://www.cloudflare.com/ips-v4 and https://www.cloudflare.com/ips-v6"
  echo
  echo "# IPv4"
  curl -fsS https://www.cloudflare.com/ips-v4 | sed '/^$/d; s|^|set_real_ip_from |; s|$|;|'
  echo "# IPv6"
  curl -fsS https://www.cloudflare.com/ips-v6 | sed '/^$/d; s|^|set_real_ip_from |; s|$|;|'
} > "$TMP"

# Refuse to overwrite with an empty/garbled download.
[ "$(grep -c '^set_real_ip_from' "$TMP")" -ge 10 ] || { echo "unexpected Cloudflare response" >&2; exit 1; }
mv "$TMP" "$OUT"
echo "updated $OUT"
